# Generated by Django 5.2.1 on 2025-06-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veluxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del producto(Opcional)'),
        ),
    ]
