# Generated by Django 5.2.1 on 2025-08-13 17:47

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veluxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen1',
            field=models.ImageField(blank=True, help_text='Esta es la imagen que aparecerá como vista previa en la tienda, debe ser la mejor.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='productos/', verbose_name='Foto o imagen'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='productos/', verbose_name='Foto o imagen 3'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='productos/', verbose_name='Foto o imagen 3'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='veluxapp.productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
