# Generated by Django 5.2.1 on 2025-08-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veluxapp', '0002_alter_productos_imagen1_alter_productos_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='linea',
            field=models.CharField(choices=[('skin', 'Chibi Skin'), ('tea', 'Chibi Tea'), ('todo', 'Todos')], default='todo', help_text='Selecciona la línea a la que pertenece este producto', max_length=10, verbose_name='Linea'),
        ),
    ]
