# Generated by Django 5.2.1 on 2025-08-17 17:21

import backend.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veluxapp', '0003_productos_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen1',
            field=models.ImageField(blank=True, help_text='Esta es la imagen que aparecerá como vista previa en la tienda, debe ser la mejor.', null=True, storage=backend.storages_backends.MediaStorage(), upload_to='productos/', verbose_name='Foto o imagen'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, storage=backend.storages_backends.MediaStorage(), upload_to='productos/', verbose_name='Foto o imagen 3'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, storage=backend.storages_backends.MediaStorage(), upload_to='productos/', verbose_name='Foto o imagen 3'),
        ),
    ]
