# Generated by Django 5.2.1 on 2026-01-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veluxapp', '0005_alter_productos_imagen1_alter_productos_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='es_producto_coreano',
            field=models.BooleanField(default=False, help_text='Marca esta casilla si el producto es de origen coreano', verbose_name='Producto de Corea'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='linea',
            field=models.CharField(choices=[('skin', 'Chibi Skin'), ('tea', 'Chibi Tea'), ('todo', 'Otros')], default='todo', help_text='Selecciona la línea a la que pertenece este producto', max_length=10, verbose_name='Linea'),
        ),
    ]
